### ISSUE TITLE
Doesn't work in macOS Safari

### ISSUE THREAD

**Issue by deepakkj** [FezVrasta/react-resize-aware#10]
I have been using React Resize Aware since sometime but have recently tested this on macOS Safari and it doesn't work at all.
It works on Chrome, IE, Firefox though.

macOS Safari version 10.1.2

**Comment by FezVrasta** [comment]
I'm able to test it on Safari 11 and it works fine, I'm not sure about that specific version but it's weird that it doesn't work. `<object />` is supported on any browser.

Can you give me more details?

**Comment by deepakkj** [comment]
Hi,

I have attached 3 screenshots for the same

1) 1-mac.png : MAC Safari issue
2) 2-chrome.png : Working fine in chrome
3) 3-code.png
<img width="1198" alt="1-mac" src="https://user-images.githubusercontent.com/9112236/32501889-46ba8ef0-c3ff-11e7-8cae-e8f175e3123c.png">
<img width="1255" alt="2-chrome" src="https://user-images.githubusercontent.com/9112236/32501893-48d58294-c3ff-11e7-8c3e-01471e46753b.png">
<img width="893" alt="3-code" src="https://user-images.githubusercontent.com/9112236/32501905-4cc45308-c3ff-11e7-893d-27e964be7160.png">


 : Code

**Comment by FezVrasta** [comment]
That's not how the component is supposed to be used.

it should be:

```
return (
  <ResizeAware style={{ position: 'relative', padding: '24px' }}>
    <div style={{ border: '1px solid red', width: '100%' }}>Hello I am ResizeAware</div>
  </ResizeAware>
)
```

**Comment by deepakkj** [comment]
Hi,

I have updated the code as you mentioned, but still it doesn't work.
I don't get any console errors as well.

Thanks

**Comment by FezVrasta** [comment]
Please provide a codepen.io example, otherwise I don't really know how to help you

**Comment by deepakkj** [comment]
Here it is [https://www.webpackbin.com/bins/-KyMGrtcrDki8rJ_vUvN](https://www.webpackbin.com/bins/-KyMGrtcrDki8rJ_vUvN)

**Comment by FezVrasta** [comment]
on Safari 11 it works just fine, are you saying it doesn't only on Safari 10?

**Comment by deepakkj** [comment]
Yes, it is on Safari 10. Let me update it to 11 and will let you know.
Thanks again

**Comment by FezVrasta** [comment]
Ok, I don't have any way to test Safari 10 unfortunately, if you know how to fix it feel free to send a PR tho.

**Comment by deepakkj** [comment]
I have updated and it works on Safari 11. Not sure why it didn't work on Safari 10.
Thanks again.
