### ISSUE TITLE
Resizing loop: suggestion for documentation

### ISSUE THREAD

**Issue by walmink** [FezVrasta/react-resize-aware#13]
I spent quite some time dealing with problem that was solved with a single line. Maybe this can be added as a caveat to the docs.

The below description is based on my specific situation, but can be generalised. I realise I may be slightly misinterpreting things, my exact understanding of what's going on inside the ResizeAware library is limited.

## Problem
- I had a `<ResizeAware>` React component with a flex-box size (height) that often resulted in fractional heights
- Inside it was an `<SVG>` component whose `viewBox` property was being updated based on the size of the `width` and `height` that came from the resize event.
- Because those numbers where rounded, the setup got stuck in a loop with an ever-increasing `<ResizeAware>` component.

## Solution
Simply applying an `overflow: hidden` to the `style` prop of the `<ResizeAware>` component seems to stop it from resizing itself based on it's contents.

**Comment by FezVrasta** [comment]
Hi, thanks for the issue, please feel free to send a PR to improve the docs!
