### ISSUE TITLE
not working on firefox

### ISSUE THREAD

**Issue by webyonet** [FezVrasta/react-resize-aware#15]
OS: Mac os high sierra
Firefox version: 61.0.1

**Comment by maxime-rainville** [comment]
I'm seeing the same thing here. https://youtu.be/_jp717mI8sM
I'm running FireFox 61.0.1 on Ubuntu. 

There's no errors log to the console.

The initial size is detected correctly, but is not updated with the browser window is resize.

**Comment by maxime-rainville** [comment]
Looks like Firefox only fires the `onload` event for `<object>` once.

**Comment by maxime-rainville** [comment]
I've reimplemented `ResizeAware` using a `ResizeObserver` polyfill for our project. https://github.com/open-sausages/silverstripe-admin/commit/6eed0bb7eb6037a8305e567c5aa2fad2291311fa

It does require an extra dependency, but it should work in all browsers. I'm happy to do a PR for this project if you want.

**Comment by FezVrasta** [comment]
I'm going to switch to a different resize detection method, I don't want extra dependencies.

**Comment by NemethNorbert** [comment]
Hey,

Any update on this issue?

**Comment by DavidHenri008** [comment]
Any news on this?

**Comment by FezVrasta** [comment]
Fixed with 2.7.2
