### ISSUE TITLE
High CPU usage viewing demo page

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/react-resize-aware#19]
https://fezvrasta.github.io/react-resize-aware/

Loading this page makes my CPU usage spike to 300%+

![cpu](https://i.gyazo.com/69c2a77f49a115c824cbdcdaaf7e60e1.gif)

Twitter vs demo

Chrome DevTools is showing repeated function calls on every frame while the page is idle.

**Comment by FezVrasta** [comment]
There may be some issue with the new implementation 🧐

**Comment by FezVrasta** [comment]
`3.0.0-beta.3` fixes this bug, I had to change the API of the hook, now it returns a node rather than a component as first element of the array
