### ISSUE TITLE
react-resize-aware does not support Firefox and Edge

### ISSUE THREAD

**Issue by abuinitski** [FezVrasta/react-resize-aware#20]
Browser: current Firefox developer edition
How to reproduce: open https://fezvrasta.github.io/react-resize-aware/
Expected result: see demo working

Observed result: blank screen, and exception inside resize listener: 
<img width="1792" alt="Снимок экрана 2019-03-12 в 20 16 01" src="https://user-images.githubusercontent.com/159410/54221010-ad867780-4503-11e9-9aee-d22c5c1a499e.png">

**Comment by abuinitski** [comment]
Clear reason is https://github.com/abuinitski/react-resize-aware/blob/3ca5bb01ec15e273aa697d2172eddfd04c6198bd/src/useOnResize.js#L9 : on Firefox object document does not have a `contentDocument` – and according to this property description, it only exists for iframes.

I can prepare a pull request, but before that: is there are reason that you've used `object` instead of `iframe`?

**Comment by FezVrasta** [comment]
Thanks for the report, `3.0.0-beta.2` should fix it.

**Comment by FezVrasta** [comment]
Actually, please use `3.0.0-beta.3`, I fixed a memory leak

**Comment by abuinitski** [comment]
thanks! confirm the issue is fixed for me 👍
