### ISSUE TITLE
Doesn't work / causes page freezes in IE 11

### ISSUE THREAD

**Issue by diondiondion** [FezVrasta/react-resize-aware#24]
To reproduce, visit https://fezvrasta.github.io/react-resize-aware/ in IE 11.

Not sure it's in the scope of this lib to support IE 11, but a warning in the readme would be nice, I just had to rip react-resize-aware out of our codebase again as it's causing errors in that browser & we have to support it. :(

**Comment by FezVrasta** [comment]
I'm not aware of any reason why it should not work, but if you are using the 3.0.0-beta.3 there's #23 where they report I may have messed up the deploy.

I will fix it as soon I get some free time to do it.

**Comment by jannisg** [comment]
@diondiondion I've had the same issue and removed this package as a dependency as well.

For what it's worth: The issue appears to be that accessing `document.contentWindow` on the `<object>` tag in IE11 triggers a security exception (`Access is denied.` in console) which breaks the plugin.

Changing the `<object data="about:blank" />` to `<iframe src="about:blank" />` makes it work in IE11 but by the time I had gotten to it it seemed easier to remove it.

**Comment by FezVrasta** [comment]
I guess we could have an option to use an iframe rather than an object, but AFAIK the performance will degrade

**Comment by jannisg** [comment]
I guess you could add a `compat` flag or something but I wouldn't bother. IE11 will hopefully drop off in terms of support soon-ish anyway :)

Was just sharing how far I got in terms of my debugging, there may even be a way to resove the issue while still using an `<object>` element but I didn't look into it much further myself.

**Comment by diondiondion** [comment]
> I will fix it as soon I get some free time to do it.

Thank you, much appreciated! I'll surely re-adopt the library once the issue has been fixed. I've worked around it for now by manually measuring a custom div. Is there anywhere I could read up on the performance benefits on measuring an object element instead? Sounds pretty interesting.

**Comment by FezVrasta** [comment]
`div` doesn't expose a `resize` event, so you need to set an interval and measure the item each X seconds. `object`, instead, emits a `resize` event just when actually needed.

**Comment by SpadarShut** [comment]
I also need to support ie11. Will you accept a PR with userAgent check and iframe rendering for IE?

**Comment by joefatora** [comment]
I believe the same error is also occurring in Firefox 68.

**Comment by joefatora** [comment]
Fixed in https://github.com/FezVrasta/react-resize-aware/pull/28

Perhaps there are tradeoffs to the iframe but it works in other browsers and does not cause a crash.

Since maintainers don't seem to care too much, you can alternatively install my fork in your `package.json` like so:
```
    "react-resize-aware": "git://github.com/altitudenetworks/react-resize-aware#bbb3a5845880383de2ba3da01f760a8bd3decaff",
```

**Comment by dohomi** [comment]
I bumped into the same issue, I had `TypeError: Cannot read property 'defaultView' of null` errors in my mobile view. The fork @joefatora fixed it for me thanks!

**Comment by FezVrasta** [comment]
Did you get it on IE or Firefox?

**Comment by dohomi** [comment]
I did not investigate any further, it was a dev project and nothing too serious for me. I just found out that if you switch to mobile the issue appeared.

**Comment by dohomi** [comment]
@FezVrasta the beta.4 was fixing it for me, thanks

**Comment by alex-gla** [comment]
beta.4 still does not work for me. @FezVrasta do you have any updates on this ?

**Comment by FezVrasta** [comment]
Please everybody try beta.5
