### ISSUE TITLE
3.0.0-beta.4 still doesn't work in Firefox

### ISSUE THREAD

**Issue by newsiberian** [FezVrasta/react-resize-aware#26]
Hi, thanks for yesterday quick response. It doesn't throw exceptions now in Firefox, but still doesn't work as expected. I'm always receives `sizes`: `width: 0`, `height: 0`. At the same time Chromium works fine.

**Comment by FezVrasta** [comment]
What version of Firefox are you using? I just tried https://fezvrasta.github.io/react-resize-aware/ on Firefox 67 and it works fine

**Comment by newsiberian** [comment]
I'm on 67.0.1

**Comment by FezVrasta** [comment]
Are you using the link I posted above to test it?

**Comment by newsiberian** [comment]
That example also works fine to me. Ok, i'll try to understand whats going on in my app

**Comment by newsiberian** [comment]
Ok, I did some investigation and here is the results:
I've added logging to `useResizeAware` like this:
```js
// The real Hook is `useResizeAware.js`
export default (ref, onResize) => {
  React.useEffect(() => {
    console.log('ref.current', ref.current);
    console.log('ref.current.contentDocument', ref.current.contentDocument);
    console.log(
      'ref.current.contentDocument.defaultView',
      ref.current.contentDocument.defaultView,
    );
    const target =
      ref.current &&
      ref.current.contentDocument &&
      ref.current.contentDocument.defaultView;
    console.log('target', target);

    // trigger onResize event on mount to provide initial sizes
    onResize();
...
```

and the results in Chromium:
![Screenshot_20190614_110108](https://user-images.githubusercontent.com/11130487/59482626-de27d580-8e93-11e9-9a25-dd60109ad87f.png)

and the same from Firefox:
![Screenshot_20190614_110159](https://user-images.githubusercontent.com/11130487/59482648-eed84b80-8e93-11e9-9d59-6e41476daf68.png)

So, sometimes `contentDocument` is not yet ready (null) to the moment when this code fired. And **it is never rerun after this**. 

@FezVrasta, any thoughts?

**Comment by newsiberian** [comment]
Doing something like this vvv solves the problem
```js
// The real Hook is `useResizeAware.js`
export default (ref, onResize) => {
  React.useEffect(() => {
    let target;

    setTimeout(() => {
      target =
        ref.current &&
        ref.current.contentDocument &&
        ref.current.contentDocument.defaultView;

      // trigger onResize event on mount to provide initial sizes
      onResize();

      target && target.addEventListener('resize', onResize);
    }, 20);
...
```

**Comment by FezVrasta** [comment]
@newsiberian may you try out this code instead please?


```js
export default (ref, onResize) => {
  React.useEffect(() => {
    const target =
        ref.current &&
        ref.current.contentDocument &&
        ref.current.contentDocument.defaultView;

    // trigger onResize event on mount to provide initial sizes
    onResize();

    target && target.addEventListener('resize', onResize);

    [...]

  }, [ref.current.contentDocument]);
```

**Comment by newsiberian** [comment]
Unfortunately, this method does not work
`Uncaught (in promise) TypeError: Cannot read property 'contentDocument' of undefined`
because initially `ref.current` is undefined

and even if I set
```js
// This automatically attaches to itself the resize event listener
// and adds onResize as callback
export default ({ onResize }) => {
  const ref = React.useRef({});
...
```
initial `ref.current` state to object it doesn't rerun `useOnResize`, when `contentDocument` became defined.
