### ISSUE TITLE
Confusing state

### ISSUE THREAD

**Issue by wijnsema** [FezVrasta/react-resize-aware#27]
Good to see new React hooks are being used. But this seems a complete rewrite. Docs are for the new version, but this is in beta! Where are the old (current!) docs?

Code management systems can do wonderful things. but this is asking to much.

My suggestion: Keep the old repo, and create a new one, react-resize-hook!

Nice software, still.

**Comment by FezVrasta** [comment]
Thanks for the suggestion, I updated the README.

https://github.com/FezVrasta/react-resize-aware/commit/39228ba4228d1212b6bfb3ff08b3a2bd8a30b6c5
