### ISSUE TITLE
Broken source map and invalid "umd:main" and "module" 

### ISSUE THREAD

**Issue by ZhangYiJiang** [FezVrasta/react-resize-aware#32]
The built package seem to have missing sourcemap - dist/index.js refers to `index.js.map`, but the file isn't in the package published on npm. 

In addition, "umd:main" and "module" in package.json refers to `foo.js`, which seems like placeholders, and should be updated to valid values, or removed.

**Comment by FezVrasta** [comment]
This should fix the issue, I'll publish the changes once I have something more to publish.

https://github.com/FezVrasta/react-resize-aware/commit/e6d133f7e0a1fcfced88ff81e52098d032e5275b
