### ISSUE TITLE
typescript usage

### ISSUE THREAD

**Issue by dohomi** [FezVrasta/react-resize-aware#35]
Hello,

Thanks for this cool little tool. Do you plan on adding typings for TypeScript? That would make the use of this plugin easier.

Cheers
Dominic

**Comment by FezVrasta** [comment]
Feel free to send a PR to add a typing file 👍

**Comment by dohomi** [comment]
@FezVrasta thanks for your reply, I swop to @rehooks/component-size which is doing basically the outcome and fits more my usecase.

**Comment by FezVrasta** [comment]
Note that the library you mentioned doesn't work for browsers that don't support the ResizeObserver API.

**Comment by dohomi** [comment]
@FezVrasta thanks for your heads up 👍 I am using the ponyfill

**Comment by OnkelTem** [comment]
I also need it in a TypeScript module of a CRA-app. It doesn't build now, failing with an error:

```
Could not find a declaration file for module 'react-resize-aware'. '/projects/.../node_modules/react-resize-aware/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-resize-aware` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-resize-aware';`  TS7016
```

@dohomi But why you have closed this issue if it wasn't resolved? :)

**Comment by dohomi** [comment]
As the maintainer mentioned: https://github.com/FezVrasta/react-resize-aware/issues/35#issuecomment-539887486
But sure I reopen it. Haven't got the chance of using this plugin
