### ISSUE TITLE
Size right now is 624 bytes

### ISSUE THREAD

**Issue by Merri** [FezVrasta/react-resize-aware#37]
It might be nice to use shield image like `https://flat.badgen.net/bundlephobia/minzip/react-resize-aware` so that description doesn't get outdated :)

Other than that this is a very nice hook!

**Comment by FezVrasta** [comment]
```
Build "useResizeAware" to dist:
        549 B: index.js.gz
        434 B: index.js.br
        560 B: index.mjs.gz
        459 B: index.mjs.br
        619 B: index.umd.js.gz
        495 B: index.umd.js.br
```

The brotli compressed version is 434 so I'd say it's still accurate. 👀

**Comment by Merri** [comment]
But that isn't the size that is comparable with other libs that provide size information. And if we made a really critical look into this then we'd notice zipped sizes are a bit hard to compare anyway since effect of compression depends on all the other code that ships in final packages.

Now that I had a look there is [`badge-size`](https://www.npmjs.com/package/badge-size) that can show all the sizes: normal, gzipped and brotli. Dunno if it'd be overkill to use all :D (Edit: Oh and you know of it already, too!)

**Comment by FezVrasta** [comment]
I changed it to 600 🤷‍♂️
