### ISSUE TITLE
react-resize-aware\src\useResizeAware.js: Unexpected token, expected "," (5:31)

### ISSUE THREAD

**Issue by hannojg** [FezVrasta/react-resize-aware#38]
Hey, 
I am getting this on a fresh react project using react 16.12 (created with `create-react-app`)
`SyntaxError: [...]\node_modules\react-resize-aware\src\useResizeAware.js: Unexpected token, expected "," (5:31)`
![image](https://user-images.githubusercontent.com/16821682/70433831-f5323380-1a82-11ea-8535-5033abf0f37a.png)

I guess that this is somewhat related to `flow` (which I don't use in my project). 
Can you please help out? Thanks a lot!

**Comment by hannojg** [comment]
Adding the source of this library to my project manually and adding flow as dependency works. So I guess there is maybe something wrong with the way this library gets packaged?

**Comment by FezVrasta** [comment]
Your project is reading from `src` rather than `dist` for some reason, the `package.json` points to `dist/index.js` as `main` entry file.

I will need a full repro to see what's wrong.

**Comment by hannojg** [comment]
It's nothing secret, I can give you access on gitlab if you have the spare time to check what's going wrong. 
I won't demand that, but I would absolutely appreciate if you find the time to do so.

**Comment by hannojg** [comment]
Silly me, I imported from the wrong path. I used 
```
import useResizeAware from "react-resize-aware/src";
```

instead of 
```
import useResizeAware from "react-resize-aware";
```
