### ISSUE TITLE
What tasks are left to do in order to take the library out of beta?

### ISSUE THREAD

**Issue by jameslnewell** [FezVrasta/react-resize-aware#39]
👋 Hello! We're considering [using this library in Gutenberg](https://github.com/WordPress/gutenberg/pull/18745#discussion_r350670391). What tasks are left to do in order to take the library out of beta? Can we assist?

**Comment by FezVrasta** [comment]
I don’t think there are any reasons to stay on beta, I’ll double check and release a stable today

**Comment by jameslnewell** [comment]
🤩 Wow thanks! Let me know if we can help in any way!

**Comment by FezVrasta** [comment]
I just released 3.0.0, please let me know if everything works as expected.
