### ISSUE TITLE
sizes are coming back with the opposite value

### ISSUE THREAD

**Issue by TerrySlack** [FezVrasta/react-resize-aware#43]
I have implemented your hook, and setup what I need in my project, based on this example

```javascript
const App = () => {
  const [resizeListener, sizes] = useResizeAware();
  
  React.useEffect(() => {
    console.log('Do something with the new size values');
  }, [sizes.width, sizes.height]);

  return (
    <div style={{ position: 'relative' }}>
      {resizeListener}
      Your content here.
    </div>
  );
}
```
In my case I only needed sizes.height.
I'm using it on an accordion, to get the height of the children components on open and close.
My issue is when I open it, I get a height of 40.  When I close it I get a height, say 100.
So it's giving me the heights, before the animation completes.  I tried using useLayoutEffect, but got the same values.  Any thoughts?

Update:  I was not using sizes.height as a dependency, as it triggers the useEffect with each pixel change.  So I was getting the backwards values, inside the useEffect, when watching the height itself being, through a useStateHook.  Once height itself changed, then it would trigger the useEffect, which is what I want.  Not a re-render on each pixel change, as the open/close animates.

I'm trying to solve the issue of resizing Accordion Sections, when a Child Accordion is placed within them and opens/closes

**Comment by FezVrasta** [comment]
May you provide a reproducible example? (codesandbox  or codepen?)
