### ISSUE TITLE
Peer dependencies error when running npm install

### ISSUE THREAD

**Issue by im-cho** [FezVrasta/react-resize-aware#52]
Bumped into this error while trying to install dependencies using `npm i`. Although I managed to solve it using `npm i --legacy-peer-deps`, But will there be any plans to update the dependencies on this project though?

![image](https://user-images.githubusercontent.com/15047293/122707978-ae371800-d28d-11eb-81b4-f685502b6a7a.png)

**Comment by RichieRunner** [comment]
same, does this work with react v18.x.x?

**Comment by FezVrasta** [comment]
I'm not sure what am I suppose to do to fix the issue?

**Comment by scinos** [comment]
I think we need to add react 17 as a peerDependency (assuming the package does work with react 17)

**Comment by FezVrasta** [comment]
Done in 3.1.1
