### ISSUE TITLE
ReferenceError: React is not defined at vendor.88501a30.js:41

### ISSUE THREAD

**Issue by wildanzrrr** [FezVrasta/react-resize-aware#57]
When I build the app, this error occurs. But if in the development stage, this error does not occur. I don't know what happened

Here is info about this error : 
`ReferenceError: React is not defined
    at vendor.88501a30.js:41
    at Object.useMemo (vendor.88501a30.js:30)
    at Object.j.useMemo (vendor.88501a30.js:12)
    at bS (vendor.88501a30.js:41)
    at $ (index.e0afc273.js:1)
    at ts (vendor.88501a30.js:30)
    at Ef (vendor.88501a30.js:34)
    at wf (vendor.88501a30.js:34)
    at Gh (vendor.88501a30.js:34)
    at zr (vendor.88501a30.js:34)`

Here is my package.json : 
`{
  "name": "evplus",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.3.1",
    "@mui/material": "^5.3.1",
    "axios": "^0.25.0",
    "js-cookie": "^3.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-multi-carousel": "^2.6.5",
    "react-resize-aware": "^3.1.1",
    "react-router-dom": "^5.3.0",
    "swiper": "^7.4.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^1.0.7",
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.15",
    "vite": "^2.7.2"
  }
}
`

And here is my jsx : 
`import React from 'react'
import { useState, useEffect } from "react"
import { Swiper, SwiperSlide } from "swiper/react"
import useResizeAware from "react-resize-aware"
import { Pagination } from "swiper"
import CardTestimony from "../util/CardTestimony"

import Avatar from "../../images/avatar.png"

import "swiper/css"
import "swiper/css/pagination"

const Testimonials = () => {
  const testimonies = [
    {
      rate: 9,
      testi:
        "Bahannya bagus, gak mengecewakan barangnya, datangnya cepet syekali terimakasih",
      pic: "src/images/avatar.png",
      name: "Vina",
      org: "BEM FILKOM",
    },
    {
      rate: 9,
      testi:
        "Seller nya langsung gece ngirimnya dan produknya bagus❤️tapi ekspedisi J&T sekarang sering bermasalah yahh Bahannya bagus, gak mengecewakan barangnya, datangnya cepet syekali terimakasih",
      pic: "src/images/avatar.png",
      name: "Utara",
      org: "Gojek",
    },
    {
      rate: 10,
      testi:
        "Seriuss ini bagus bgtt lucu gitu loh yaampun, mana harganya murah lagi dan terjangkau",
      pic: "src/images/avatar.png",
      name: "Wildann",
      org: "Tokopedia",
    },
    {
      rate: 8,
      testi:
        "Bagus bgt produknya dan emg udh kepengen beli dr kapan tau. Pengiriman agak lama tapi ini bukan salah sellernya ya",
      pic: "src/images/avatar.png",
      name: "Dilla",
      org: "MalangFood",
    },
    {
      rate: 9,
      testi:
        "sorry gak ad fotonya. punya ponakan udh dkasih gak sempet kefoto tp barangnya oke punyaaaa😍😍😍",
      pic: "src/images/avatar.png",
      name: "Wisnu",
      org: "Boss NFT",
    },
  ]

  const [resizeListener, sizes] = useResizeAware()
  const [view, setView] = useState(3)
  const [space, setSpace] = useState(20)

  useEffect(() => {
    if (sizes.width >= 1024) {
      setSpace(150)
      setView(3)
    }else if (sizes.width >= 768) {
      setSpace(250)
      setView(3)
    }else if (sizes.width >= 640) {
      setSpace(100)
      setView(2)
    }else {
      setView(1)
    }
  }, [sizes])

  return (
    <div className="flex flex-col w-full justify-center items-center my-10">
      {resizeListener}
      <div className="flex items-center justify-center">
        <h2 className="flex justify-center items-center font-bold text-4xl">
          TESTIMONIALS
        </h2>
      </div>

      <div className="flex flex-row w-11/12 items-center justify-center">
        <Swiper
          slidesPerView={view}
          centeredSlides={true}
          spaceBetween={space}
          grabCursor={true}
          pagination={{
            clickable: true,
          }}
          modules={[Pagination]}
          className="mySwiper w-full my-10"
        >
          {testimonies.map((res, id) => {
            return (
              <SwiperSlide key={id}>
                <CardTestimony
                  rate={res.rate}
                  testi={res.testi}
                  pic={res.pic}
                  name={res.name}
                  org={res.org}
                />
              </SwiperSlide>
            )
          })}
        </Swiper>
      </div>
    </div>
  )
}

export default Testimonials
`

**Comment by FezVrasta** [comment]
It seems to be an issue with your build setup, I'm unable to help with it, sorry.

**Comment by samueljseay** [comment]
@FezVrasta I'm having this issue too in Vite. It seems problematic that you use jsx in a file with just a `.js` extension?
