### ISSUE TITLE
ES7 decorators only for class declaration

### ISSUE THREAD

**Issue by chiss2906** [FezVrasta/react-resize-aware#8]
In the Usage Decorator/enhancer example the ES7 decorator is being used with a stateless component. It should be attached to a class declaration.

The wrong example:
<img width="917" alt="screen shot 2017-08-18 at 10 53 01" src="https://user-images.githubusercontent.com/3668084/29451584-783f30fc-8403-11e7-9246-a1d8ad9ddfcb.png">

**Comment by FezVrasta** [comment]
Is it required by the decorator syntax?

**Comment by chiss2906** [comment]
Yes. You can check it here: https://tc39.github.io/proposal-decorators/.
